hist(cars$Price)
hist(log(cars$Price))
boxplot(cars$Price)
boxplot(log(cars$Price))
cars$Price = log(cars$Price)
pairs(cars[, c("Price", "MPG.city", "Horsepower")])
boxplot(cars$Price ~ cars$Origin)
boxplot(cars$Price ~ cars$AirBags)
plot(cars$Price ~ cars$MPG.city, col = cars$Origin)
plot(cars$Price ~ cars$MPG.city, col = cars$AirBags)
plot(cars$Price ~ cars$Horsepower, col = cars$Origin)
plot(cars$Price ~ cars$Horsepower, col = cars$AirBags)
m = lm(Price ~ MPG.city * Origin + MPG.city * AirBags + Horsepower * Origin + Horsepower * AirBags, data = cars)
summary(m)
m2 = lm(Price ~ Horsepower * Origin + MPG.city * AirBags, data = cars)
summary(m2)
anova(m2, m)
par(mfrow=c(2, 2))
plot(m2)

library(splines)
sp = smooth.spline(x = cars$MPG.city, y = cars$Price, cv = TRUE)
sp
library(gam)
m3 = gam(Price ~ s(MPG.city, 4) + AirBags + Origin + Horsepower, data = cars)
summary(m3)
m4 = gam(Price ~ s(MPG.city, 4) * AirBags + Origin * Horsepower, data = cars)
summary(m4)
anova(m3, m4)
plot(m4, se = TRUE)


par(mfrow=c(1, 1))
library(glmnet)
y = cars$Price
x = model.matrix(Price ~ ., data = cars)[, -1]
m_ridge = glmnet(x, y, alpha = 0)
plot(m_ridge, xvar = "lambda")
ridge_cv = cv.glmnet(x, y, alpha = 0)
ridge_cv$lambda.min
m_ridge = glmnet(x, y, alpha = 0, lambda = ridge_cv$lambda.min)
coef(m_ridge)
m_lasso = glmnet(x, y, alpha = 1)
plot(m_lasso, xvar = "lambda")
lasso_cv = cv.glmnet(x, y, alpha = 1)
m_lasso = glmnet(x, y, alpha = 1, lambda = lasso_cv$lambda.min)
coef(m_lasso)

plot(y ~ predict(m_lasso, newx = x))
abline(0, 1)
plot(y ~ predict(m, newx = x))
abline(0, 1)
sum((y - predict(m, newx = x))^2)
sum((y - predict(m_lasso, newx = x))^2)
sum((y - predict(m_ridge, newx = x))^2)
