rm(list = ls())
Cement = read.table("hald.dat")
View(Cement)
colnames(Cement) = c("heat", "cal_alu", "tric_sil", "tric_fer", "dic_sil")
attach(Cement)
boxplot(Cement$heat)
pairs(Cement)
plot(dic_sil, heat)

model = lm(heat ~ cal_alu, data = Cement)
summary(model)
model2 = lm(heat ~ cal_alu + tric_sil, data = Cement)
summary(model2)
model3 = lm(heat ~ cal_alu + tric_sil + tric_fer + dic_sil, data = Cement)
summary(model3)
cor(Cement)
standard.resid = rstandard(model2)
pred = fitted(model2)
par(mfrow = c(2, 2))
plot(standard.resid)
abline(h=0, lty = 2)
plot(pred, standard.resid, xlab = "Predictions")
abline(h=0, lty = 2)
plot(cal_alu, standard.res)
abline(h=0, lty = 2)
plot(tric_sil, standard.res)
abline(h=0, lty = 2)