rm(list = ls())
library(rattle.data)
attach(wine)
dim(wine)
barplot(table(Type))
pie(table(Type))
pairs(wine[, 2:7])
pairs(wine[, 8:13])
library(MASS)
wine.lda = lda(Type ~ ., data = wine)
wine.lda
plot(wine.lda)
wine.previsioni = predict(wine.lda)
ldahist(data = wine.previsioni$x[, 1], g = wine$Type)
ldahist(data = wine.previsioni$x[, 2], g = wine$Type)
