library(ISLR)
attach(Auto)
m = lm(mpg~horsepower)
summary(m)
predict(m, data.frame(horsepower=c(98)), interval="confidence")
predict(m, data.frame(horsepower=c(98)), interval="prediction")
plot(horsepower, mpg)
abline(m)
par(mfrow=c(2,2))
plot(m)
