library(ISLR)
attach(Auto)
pairs(Auto)
cor(subset(Auto, select=c(displacement, weight, year, origin))) # correlation of subset
m = lm(mpg~.-name, data=Auto)
summary(m)
par(mfrow=c(2, 2))
plot(m)
summary(lm(mpg~displacement:weight+year:origin, data=Auto))
summary(lm(mpg~log(weight)+sqrt(horsepower)+acceleration+I(acceleration^2), data=Auto))
